### ISSUE TITLE
希望在github release提供打包好的exe

### ISSUE THREAD

**Issue by lingr7** [ITerydh/OCRandQPTandIS#1]
感谢开发，在https://github.com/PaddlePaddle/PaddleOCR/issues/4982#4 看到本项目，
github有release分发软件安装包的功能。

**Comment by ITerydh** [comment]
额，我希望是大家可以自己操作完成，这个内容挺简单的，自己去下载下来操作一下挺好的。整个exe文件夹太大，因为包含了飞桨的各种库还有cuda，上传至github不太合适。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月12日(周四) 中午12:35
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [ITerydh/OCRandQPTandIS] 希望在github release提供打包好的exe (Issue #1)




 
感谢开发，在PaddlePaddle/PaddleOCR#4982 (comment) 看到本项目，
 github有release分发软件安装包的功能。

**Comment by lingr7** [comment]
那好吧。
